###   iLogic Collector   ###
[decimal]$version = 1.0
#
# Matthew D. Jordan
# https://github.com/jordanrobot/iLogicCollector
# MIT License

#Get directory name, compile file name
$directoryName = pwd | Select-Object | %{$_.ProviderPath.Split("\")[-1]}
$compileFile = ((pwd).path + "\" + $directoryName + ".iLogicVB")

#get the files in the current directory (recursive)
$fileList = Get-ChildItem -Path $pwd -File -Recurse -Name

#test if the file is in the current directory, remove if not
If (test-path $compileFile) {
	Remove-Item -path $compileFile
}

#Create our temporary holding array, add the header...
[System.Collections.ArrayList]$tempFile = (("'This file has been auto-generated by Ilogic Collector version " + $version), ("'Collection timestamp: " + (get-date -Uformat "%Y/%m/%d - %R")), "'2020 Matthew D. Jordan - https://github.com/jordanrobot","")


$fileList | ForEach-Object -process{

	If (test-path $_) {
	
		If ((Get-Content $_ -TotalCount 1) | Select-String -Pattern "<\/iLogicCollectorHeader>" -quiet) {
			#Write filename
			$tempFile += ("'" + $_.Path)
			#Write contents
			$tempFile += (Get-Content $_)
			#Write new line
			$tempFile += ""
		}
	}
}

$fileList | Sort-Object -Descending FullName | ForEach-Object -process{

	If (test-path $_) {
	
		If ((Get-Content $_ -TotalCount 1) | Select-String -Pattern "<\/iLogicCollector>" -quiet) {
			$tempFile += (Get-Content $_)
			$tempFile +=  ""
		}
	}
}

#populate the collected Ilogic File...

$tempFile | Foreach-object -Process {

	If ($_ | Select-String -Pattern "<\/iLogicCollectorHide>" -quiet) {
		#Hide tag found, connect out line...
		Add-Content $compileFile ("'" + $_)
	} Elseif ($_ | Select-String -Pattern "<\/iLogicCollector>" -quiet) {
		#IlogicCollector tag found, skip this line
	}
	Else {
		#normal line, add to the file
		(Add-Content $compileFile $_)
	}
}